title: Zhenkun Lu's Homepage
page-top-title: Zhenkun Lu
top-section-bg-text: Macroeconomics, Public Finance
home-subtitle: Zhenkun Lu&ensp;|&ensp;陸震坤 (リク・シンコン)
copyright-text: '&copy; Zhenkun Lu 2025-. All Rights Reserved.'
